language: ruby
cache: bundler

# script: bundle exec rake test TESTOPTS=-v

# http://rubies.travis-ci.org/
# See here for osx_image -> OSX versions: https://docs.travis-ci.com/user/languages/objective-c
matrix:
  include:
    - rvm: 2.4.9
      os: linux
      env: USE_CAPNG=false
    - rvm: 2.4.9
      os: linux-ppc64le
      env: USE_CAPNG=false
    - rvm: 2.5.7
      os: linux
      env: USE_CAPNG=false
    - rvm: 2.5.7
      os: linux
      arch: s390x
      dist: xenial
      env: USE_CAPNG=false
    - rvm: 2.6.5
      os: linux
      env: USE_CAPNG=false
    - rvm: 2.6.6
      os: linux
      env: USE_CAPNG=true
    - rvm: 2.7.0
      os: linux
      env: USE_CAPNG=false
    - rvm: ruby-head
      os: linux
      env: USE_CAPNG=false
    - rvm: ruby-head
      os: linux-ppc64le
      env: USE_CAPNG=false
    - rvm: 2.4.6
      os: osx
      osx_image: xcode8.3 # OSX 10.12
      env: USE_CAPNG=false
    - rvm: ruby-head
      os: osx
      osx_image: xcode8.3 # OSX 10.12
      env: USE_CAPNG=false
  allow_failures:
    - rvm: 2.4.6
      os: osx
      osx_image: xcode8.3
      env: USE_CAPNG=false
    - rvm: 2.5.7
      os: linux
      arch: s390x
      dist: xenial
      env: USE_CAPNG=false
    - rvm: ruby-head
      env: USE_CAPNG=false

branches:
  only:
    - master

before_install: |
  gem update --system=3.1.2
  if [[ x"${USE_CAPNG}" == "xtrue" ]]; then
    echo 'gem "capng_c"' >> Gemfile.local
  fi

sudo: false
dist: trusty # for TLSv1.2 support

addons:
  apt:
    packages:
      - libgmp3-dev
      - libcap-ng-dev
