blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://groups.google.com/forum/#!forum/fluentd
    about: I have questions about Fluentd and plugins. Please ask and answer questions here
