name: Testing on Windows

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.7', '2.6', '2.5']
        os:
          - windows-latest
        experimental: [false]
        include:
          - ruby-version: '3.0'
            os: windows-latest
            experimental: true

    name: Unit testing with Ruby ${{ matrix.ruby-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: ridk exec bundle install
      - name: Run tests
        run: bundle exec rake test TESTOPTS=-v
